services:
  - type: web
    name: orange-counter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
